name: websocket_echo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  injectable: ^2.5.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  network_logger: ^1.0.4
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.2
  envied: ^1.1.1
  envied_generator: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9
  injectable_generator: ^2.0.0

flutter:
  uses-material-design: true
